baseURL: https://siqiong-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Siqiong ZHOU
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      welcome to my website: a bilibili vlogger and cosplay lover
    title: Hi, my name is Siqiong
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Glentworth Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: szhou.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (44) 07410901206
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    # copyright: Company Name
    # enable: yes
    # quicklinks:
    #   - alt: HTML5 UP
    #     text: 'Design: '
    #     url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #   label: Twitter
      #   url: https://www.twitter.com
      # - icon: fa-facebook
      #   label: Facebook
      #   url: https://www.facebook.com
      # - icon: fa-instagram
      #   label: Instagram
      #   url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/Siqiong-zhou/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/%E6%96%AF%E7%90%BC-%E5%91%A8-452703163/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      # - name: Generic Blog
      #   url: blogs/ipsum
      # - name: Elements
      #   url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: about_me.jpg
        subtitle: Something about Me
        title: About Me
        url: blogs/about_me
      - image: resume.jpg
        subtitle: My Resume
        title: Resume
        url: blogs/resume
      - image: cosplay.jpg
        subtitle: some characters that I cosplayed
        title: cosplay
        url: blogs/cosplay
      - image: bilibili_vlog.jpg
        subtitle: Videos I took
        title: Bilibili Vlog
        url: blogs/bilibili_vlog
      - image: exchange_life.jpg
        subtitle: My Exchange Experience in Canada
        title: Exchange Life
        url: blogs/exchange_life
      - image: R_studio.jpg
        subtitle: Something I learnt in this class
        title: R Studio
        url: blogs/R_studio
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
